Run flake8 across this codebase
gforcada/flake8-deprecated pull request #16
Opened 2017-10-23 07:14 UTC by alexmuller

flake8 spotted that there was a duplicate entry in the dictionary so it's probably worth running as part of the tests.

I don't know tox at all so I may have done this in the wrong place.

2017-10-23 20:58 UTC, gforcada requested changes
Thanks for spending the time cleaning up my mess!! 🎉 

There's a couple of small changes I would like to make on your changes, if you wish I can do them myself if you want. Just let me know.

Again, thanks for caring so much to send a couple of pull requests already!!

2017-10-23 20:58 UTC, gforcada commented on setup.cfg
> +max-line-length=100
Would you mind changing that to 80? I usually work with two or three editors one next to each other and 80 is the perfect size for that.

2017-10-23 20:58 UTC, gforcada commented on tox.ini
> +    flake8
That does not work, you should instead put ``flake8 *.py``

2017-10-30 07:54 UTC, alexmuller commented
No problem at all! Updated this pull request, sorry for the delay :)

2017-10-31 16:32 UTC, merged

2017-10-31 16:33 UTC, gforcada commented
@alexmuller thanks!  I will release it shortly, ping me back if I did not do it.

2017-10-31 16:38 UTC, gforcada commented
@alexmuller released 1.3 let me know if something is broken 🙂